### ISSUE TITLE
Consul 0.7.0

### ISSUE THREAD

**Issue by ruslansennov** [pszymczyk/embedded-consul#20]
New version released.
Do you plan to bump it?

**Comment by pszymczyk** [comment]
Yes I will bump Consul in coming days.   

At the moment you can specify consul version using builder:

`ConsulStarterBuilder withConsulVersion(String consulVersion) { ...`

**Comment by ruslansennov** [comment]
Hi @pszymczyk 
Vesrion 0.2.0 is still unavailable on maven central

**Comment by pszymczyk** [comment]
I know, there are some problems with running embedded-consul-0.2.0 on Mac OS X Sierra.

**Comment by jpaern** [comment]
Hi pszymczyk,
Any idea when Version 0.2.0 will hit maven central?

**Comment by pszymczyk** [comment]
Good news! I've setup new Linux machine to upload archives, version 0.2.0 is in mvn central now: http://central.maven.org/maven2/com/pszymczyk/consul/embedded-consul/0.2.0/. Due to bug in Consul embedded-consul still does not work properly on Mac OS X sierra but you can use 0.2.0 on every other os :).
